name: Test Actions

on:
  push:
    branches: ["master"]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: 'echo "✅ Actions сработал! Commit: $GITHUB_SHA"'
